### ISSUE TITLE
Skipping the test file without any error

### ISSUE THREAD

**Issue by c-science1** [skovhus/jest-codemods#103] opened 2018-02-21 12:11 UTC
I am running  jest-codemods src/app/page-components/login/forgot-password/*.spec.ts --force
but getting the result below without any transformation happening or helpful message

$ jest-codemods src/app/page-components/login/forgot-password/*.spec.ts --force
? Which test library would you like to migrate from? Jasmine: this usage
? Will you be using Jest on Node.js as your test runner? Yes, use the globals provided by Jest (recommend
ed)
WARNING: Git directory is not clean. Forcibly continuing.
Executing command: jscodeshift -t C:\Users\Sarah.Saad\AppData\Roaming\npm\node_modules\jest-codemods\dist\
transformers\jasmine-this.js src/app/page-components/login/forgot-password/forgot-password.component.spec.
ts
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
All done.
Results:
0 errors
0 unmodified
1 skipped
0 ok
Time elapsed: 1.041seconds

**Comment by skovhus** [comment] 2018-02-21 12:25
We currently don't support TypeScript. But you can try with `--parser flow`

Duplicate of https://github.com/skovhus/jest-codemods/issues/102

**Closed by skovhus** 2018-02-21 12:25 UTC

**Comment by c-science1** [comment] 2018-02-21 12:52
Thanks for getting back. However, I was really hoping to find a workaround to able to convert my jasmine tests to Jest.

Even with --parse flow the file is getting skipped

![image](https://user-images.githubusercontent.com/19345360/36480919-fa4c402c-1705-11e8-8fe3-04c2d23a39b1.png)

**Comment by skovhus** [comment] 2018-02-21 13:24
Try renaming the file to `.js` and see if that works. If not can you paste the content here?

**Comment by c-science1** [comment] 2018-02-21 13:32
here is the screenshot of Jasmin test file

![image](https://user-images.githubusercontent.com/19345360/36482566-ac59c87a-170b-11e8-9aeb-5bc39cde0a35.png)
